### ISSUE TITLE
no submission possible

### ISSUE THREAD

**Issue by diemmarkus** [Transkribus/competitions#113]
Hi,

a participant of cBAD has reported, that they get this message:
````
"You have recently submitted a method.
Competition policy is at most one submission per *20 minutes*. Please
re-submit at a later time.". 
````
when they try to submit new results although they last submitted 4 days ago.

thanks for looking into it

cheers,
markus

**Comment by sfikas** [comment]
I couldn't reproduce the bug - everything apparently works ok. (solved with the commit fixing #109..??)

However now I have an email sent automatically to me whenever someone gets his submission restricted. The email contains some debugging info, so it'll be easier to find out the cause of the error.

@diemmarkus , you may turn on the time restriction again if you want.

**Comment by sfikas** [comment]
There is also a chance that the cause of the error is the 'auto_add_now' flag. There is a long-time discussion over the django community whether to deprecate the flag, cf. https://code.djangoproject.com/ticket/22995

**Comment by diemmarkus** [comment]
Thanks for looking into it!

**Comment by diemmarkus** [comment]
Hi,

did you receive an e-mail? - It seems like the bug is still there...

cheers,
markus

**Comment by sfikas** [comment]
Hi,
Yes it looks like the bug is there. I have an idea of what the problem
might be though. Please dont set the limit to zero just yet - if i m right,
the user should be able to submit (despite the bug). Ill look into it asap.

Στις 5 Ιουλ 2017 12:05, ο χρήστης "Markus Diem" <notifications@github.com>
έγραψε:

**Comment by sfikas** [comment]
The error was related to way time difference was evaluated -- the correct way is https://docs.python.org/3/library/datetime.html#datetime.timedelta.total_seconds
and not datetime.timedelta.seconds .
The latter would work only for time differences less than a day - for dt more than a day, this would wrap around to zero, hence the error.

**Comment by diemmarkus** [comment]
cool! thanks for looking into it...
